### ISSUE TITLE
`update` operator's type improvements

### ISSUE THREAD

**Issue by dovranJorayev** [igorkamyshev/farfetched#432] opened 2024-01-24 19:10 UTC
Due typescript type constraints in `update` operator, unable to pass result field of return type of `by.success` method.
```ts
update(getEntityDetailedQuery, {
    on: patchEntityMutation,
    by: {
        success({query, mutation}) { // TS error here as result always required
            if (query && 'result' in query) {
                return {
                    result: {...query.result, ...mutation.params.data}
                }
            }
            return {
                result: null, // in case of query not exist 
                refetch: true
            }
        }
    }
})
```
[Playground link](https://www.typescriptlang.org/play?ts=5.2.2&ssl=32&ssc=3&pln=17&pc=1#code/JYWwDg9gTgLgBAbwMZQKYEMaoIoFdVQCeANHChlgLK4ybAQB2puYAJpqgL5wBmUEIOAHIAAj3RQeqGEgAWqVgHok0VEIDcAKFCRYichwCiPKUhjc+A4ahOoz0DZs0xCYVHEMMYwFwBFp6MAANgpwALyImnDRcMCsAFxwDLggAEYEWjFwuAwQiQDOMFDADADmmTGsuHlwhcVlFdFFqAVFJeWanE4qDIVwpdKe3i4AQoQAkqwAYgAe4WRoRrZmADwIqF4+EwlJKelQnKRDW-60wQoAfAAUAJRaPX0DMMd+AeeseASE8wZYn0RXBCydAMVghKCJJ4vQhjSazTh3bqMPpgTByaGzH6LLDGUwwNYbYbbRLJNIZODsWiJAAKEm86CCK2hp0CIVYF0O2QYAGtcgB3BjXREPeComSyaHUWjeRhYiioKV0RiA4Gg8GJMXozYueGIzQsSmoK5Q7WEFnvf4kSJZRgatES02KmVMKIxVKERIIV1ZaL5XBIJCofL5QEAR3wRFIIBoSoYCMQcEUijgABUAMpwAj8KBweRoODofJwNB+oLwBl89CEItocPANCsb0+rLAHhwK7hr5wABk3eEJdwZaEsQYcE7RBu1ub0+iaBguCgo69M5XMQHZc9ADpt+PCJv1zBSNvN9HpfQGJvUVB0CB8pvKeguqvm0-n6-V3OF0um8-i0HBzAJKDkEpBJiOZCFu4EBtruSQQPAqAzMAfQ-s+aBSOKiRFPgqEvrhcDvgRnQ3JoQA)

[Additional info from official effector telegram group](https://t.me/effector_ru/333572)

**Comment by dovranJorayev** [comment] 2024-01-24 19:15
Currently update always forces to pass full data structure of query. So cases when mutation result does not have full data types for the query it is impossible to implement without type assertions
```ts
update(getEntityDetailedQuery, {
    on: patchEntityMutation,
    by: {
        success({query, mutation}) { // TS error here as result always required
            if (query && 'result' in query) {
                return {
                    result: {...query.result, ...mutation.params.data}
                }
            }
            return {
                result: null as never, // workaround in user land code
                refetch: true
            }
        }
    }
})
```

**Comment by igorkamyshev** [comment] 2024-01-27 15:58
Duplicate of https://github.com/igorkamyshev/farfetched/issues/397

**Closed** 2024-01-27 15:58 UTC
Labels: type:bug, good first issue, scope:core
